http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: false
        frameDeny: false
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"

    rate-limit:
      rateLimit:
        average: 500
        burst: 200
        period: 1s

    traefik-auth:
      basicAuth:
        users:
          - "admin:$apr1$stlxSCoh$MII0dN6SITBq9pSb8tkBB."
