tls:
  certificates:
    - certFile: /etc/traefik/certs/pulse.crt
      keyFile: /etc/traefik/certs/pulse.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/pulse.crt
        keyFile: /etc/traefik/certs/pulse.key
http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 0
        stsIncludeSubdomains: false
        stsPreload: false
        frameDeny: false          # ← changer true en false
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"

    rate-limit:
      rateLimit:
        average: 500
        burst: 200
        period: 1s
