http:
  routers:
    traefik-dashboard:
      rule: "Host(`traefik.pulse.local`)"
      entryPoints:
        - websecure
      service: api@internal
      tls: {}
      middlewares:
        - traefik-auth
        - security-headers
    keycloak:
      rule: "Host(`auth.pulse.local`)"
      entryPoints:
        - websecure
      service: keycloak-service
      tls: {}
      middlewares:
        - security-headers
    prometheus:
      rule: "Host(`prometheus.pulse.local`)"
      entryPoints:
        - websecure
      service: prometheus-service
      tls: {}
      middlewares:
        - security-headers
        - rate-limit
    grafana:
      rule: "Host(`grafana.pulse.local`)"
      entryPoints:
        - websecure
      service: grafana-service
      tls: {}
      middlewares:
        - security-headers
    wazuh:
      rule: "Host(`wazuh.pulse.local`)"
      entryPoints:
        - websecure
      service: wazuh-service
      tls: {}
      middlewares:
        - security-headers
    frontend:
      rule: "Host(`ai.pulse.local`)"
      entryPoints:
        - websecure
      service: frontend-service
      tls: {}
      middlewares:
        - security-headers

  services:
    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://pulse_keycloak:8080"
    prometheus-service:
      loadBalancer:
        servers:
          - url: "http://pulse_prometheus:9090"
    grafana-service:
      loadBalancer:
        servers:
          - url: "http://pulse_grafana:3000"
    wazuh-service:
      loadBalancer:
        servers:
          - url: "http://wazuh-dashboard:5601"
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://pulse_frontend:5173"

  middlewares:
    traefik-auth:
      basicAuth:
        users:
          - "admin:$apr1$stlxSCoh$MII0dN6SITBq9pSb8tkBB."
