"""add template asset

Revision ID: 10e5dba6044c
Revises: de48f179c060
Create Date: 2026-06-16 21:22:37.734320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e5dba6044c'
down_revision: Union[str, Sequence[str], None] = 'de48f179c060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('responsible_role', sa.String(), nullable=True),
    sa.Column('required_variables', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=True)
    op.create_table('template_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_assets_key'), 'template_assets', ['key'], unique=True)
    op.create_table('document_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('document_type_id', sa.String(), nullable=False),
    sa.Column('base_template_id', sa.String(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['base_template_id'], ['base_templates.id'], ),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE documents SET status = 'validated' WHERE status IS NULL")
    op.alter_column('documents', 'status', nullable=False)
    op.add_column('documents', sa.Column('employee_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('document_type_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'documents', 'document_types', ['document_type_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'document_type_id')
    op.drop_column('documents', 'employee_id')
    op.drop_column('documents', 'status')
    op.drop_table('document_templates')
    op.drop_index(op.f('ix_template_assets_key'), table_name='template_assets')
    op.drop_table('template_assets')
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_table('base_templates')
    # ### end Alembic commands ###
