"""Add author_name and Document

Revision ID: 4821a85a03f4
Revises: 9208e1f92685
Create Date: 2026-06-12 03:42:29.019087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4821a85a03f4'
down_revision: Union[str, Sequence[str], None] = '9208e1f92685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_department_manager', 'departments', 'employees', ['manager_id'], ['id'], use_alter=True)
    op.add_column('import_history', sa.Column('author_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_history', 'author_name')
    op.drop_constraint('fk_department_manager', 'departments', type_='foreignkey')
    op.drop_table('documents')
    # ### end Alembic commands ###
