"""Add ImportHistory table

Revision ID: 9208e1f92685
Revises: f6ce05275455
Create Date: 2026-06-12 02:58:27.768462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9208e1f92685'
down_revision: Union[str, Sequence[str], None] = 'f6ce05275455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('processed_lines', sa.Integer(), nullable=True),
    sa.Column('created_lines', sa.Integer(), nullable=True),
    sa.Column('updated_lines', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('full_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_department_manager', 'departments', type_='foreignkey')
    op.drop_table('import_history')
    # ### end Alembic commands ###
