"""make fks nullable

Revision ID: a1e96e4c6939
Revises: ba907843172c
Create Date: 2026-06-17 12:12:12.295129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e96e4c6939'
down_revision: Union[str, Sequence[str], None] = 'ba907843172c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_recipient_states', 'alert_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('attendances', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('career_paths', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chat_messages', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contracts', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document_access_events', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document_templates', 'document_type_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('document_templates', 'base_template_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_benefits', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_benefits', 'benefit_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_skills', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employee_skills', 'skill_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('engagement_events', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('engagement_snapshots', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interviews', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interviews', 'manager_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leaves', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mobility_requests', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('performance_objectives', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('performance_reviews', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('prediction_snapshots', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project_assignments', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project_assignments', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('promotion_history', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_enrollments', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_enrollments', 'training_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workflow_steps', 'workflow_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workflows', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workflow_steps', 'workflow_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_enrollments', 'training_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_enrollments', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('promotion_history', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project_assignments', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project_assignments', 'project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('prediction_snapshots', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('performance_reviews', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('performance_objectives', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mobility_requests', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leaves', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interviews', 'manager_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interviews', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('engagement_snapshots', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('engagement_events', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_skills', 'skill_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_skills', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_benefits', 'benefit_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employee_benefits', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document_templates', 'base_template_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document_templates', 'document_type_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('document_access_events', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contracts', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat_messages', 'conversation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('career_paths', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('attendances', 'employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alert_recipient_states', 'alert_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
