"""add_ml_module_configs

Revision ID: ba907843172c
Revises: 10e5dba6044c
Create Date: 2026-06-17 01:06:16.457106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba907843172c'
down_revision: Union[str, Sequence[str], None] = '10e5dba6044c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_module_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('strict_mode', sa.Boolean(), nullable=True),
    sa.Column('heuristic_params', sa.JSON(), nullable=True),
    sa.Column('ml_params', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_status', sa.String(), nullable=True),
    sa.Column('training_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_module_configs_module_id'), 'ml_module_configs', ['module_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_module_configs_module_id'), table_name='ml_module_configs')
    op.drop_table('ml_module_configs')
    # ### end Alembic commands ###
