"""Add ai_observability_events table

Revision ID: de48f179c060
Revises: f6a9b3d4c1e2
Create Date: 2026-06-16 01:41:58.189826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de48f179c060'
down_revision: Union[str, Sequence[str], None] = 'f6a9b3d4c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_observability_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_observability_events_user_id'), 'ai_observability_events', ['user_id'], unique=False)
    op.create_table('prediction_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('prediction_type', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('factors_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_snapshots_employee_id'), 'prediction_snapshots', ['employee_id'], unique=False)
    op.add_column('alert_recipient_states', sa.Column('status', sa.String(), nullable=False))
    op.drop_constraint(op.f('alert_recipient_states_alert_id_fkey'), 'alert_recipient_states', type_='foreignkey')
    op.create_foreign_key(None, 'alert_recipient_states', 'alerts', ['alert_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_data_access_policy_scope_field_role'), 'data_access_policies', type_='unique')
    op.alter_column('documents', 'rag_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('import_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('skills', 'is_certifiable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('skills', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(op.f('user_preferences_user_id_key'), 'user_preferences', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_preferences_user_id_key'), 'user_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('skills', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('skills', 'is_certifiable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('import_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'rag_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_data_access_policy_scope_field_role'), 'data_access_policies', ['resource', 'scope', 'field_key', 'role'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'alert_recipient_states', type_='foreignkey')
    op.create_foreign_key(op.f('alert_recipient_states_alert_id_fkey'), 'alert_recipient_states', 'alerts', ['alert_id'], ['id'])
    op.drop_column('alert_recipient_states', 'status')
    op.drop_index(op.f('ix_prediction_snapshots_employee_id'), table_name='prediction_snapshots')
    op.drop_table('prediction_snapshots')
    op.drop_index(op.f('ix_ai_observability_events_user_id'), table_name='ai_observability_events')
    op.drop_table('ai_observability_events')
    # ### end Alembic commands ###
