from datetime import date


DEMO_USERS = [
    {
        "id": "emp-demo-youssef",
        "email": "youssef.benali@pulse.ma",
        "first_name": "Youssef",
        "last_name": "Benali",
        "department": "IT & Engineering",
        "job_title": "Software Engineer",
        "manager_email": "fatima.alaoui@pulse.ma",
        "status": "actif",
        "contract_type": "CDI",
        "salary": 48000,
        "hire_date": date(2026, 5, 12),
    },
    {
        "id": "emp-demo-fatima",
        "email": "fatima.alaoui@pulse.ma",
        "first_name": "Fatima",
        "last_name": "Alaoui",
        "department": "IT & Engineering",
        "job_title": "Engineering Manager",
        "manager_email": "sara.bennani@pulse.ma",
        "status": "actif",
        "contract_type": "CDI",
        "salary": 72000,
        "hire_date": date(2025, 11, 3),
    },
    {
        "id": "emp-demo-karim",
        "email": "karim.tazi@pulse.ma",
        "first_name": "Karim",
        "last_name": "Tazi",
        "department": "Ressources Humaines",
        "job_title": "Responsable RH",
        "manager_email": "sara.bennani@pulse.ma",
        "status": "actif",
        "contract_type": "CDI",
        "salary": 68000,
        "hire_date": date(2024, 9, 2),
    },
    {
        "id": "emp-demo-sara",
        "email": "sara.bennani@pulse.ma",
        "first_name": "Sara",
        "last_name": "Bennani",
        "department": "Direction Générale",
        "job_title": "Directrice des opérations RH",
        "manager_email": None,
        "status": "actif",
        "contract_type": "CDI",
        "salary": 98000,
        "hire_date": date(2023, 4, 10),
    },
    {
        "id": "emp-demo-admin",
        "email": "admin.tech@pulse.ma",
        "first_name": "Admin",
        "last_name": "Technique",
        "department": "IT & Engineering",
        "job_title": "Administrateur Système",
        "manager_email": "sara.bennani@pulse.ma",
        "status": "actif",
        "contract_type": "CDI",
        "salary": 65000,
        "hire_date": date(2024, 1, 15),
    },
]

