requirepass PulseRH_Redis_2026!Secure
bind 0.0.0.0
protected-mode yes

rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command DEBUG ""
rename-command CONFIG "REDIS_CONFIG_SECURISE"
rename-command SHUTDOWN "REDIS_SHUTDOWN_SECURISE"

maxmemory 200mb
maxmemory-policy allkeys-lru

save 900 1
save 300 10

loglevel notice
timeout 300
tcp-keepalive 60
